name: Run the templating

on: [push]

jobs:
  run-templating:
    # Don't run this in the template repo or more than once in the forked repo
    if: ${{ github.repository != 'imlunahey/ts-template' && contains(github.repository, '/template') }}
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i handlebars
      # Run the templating
      - run:
          node ./.github/workflows/templating.mjs
      # Reset git
      - run:
          git update-ref -d HEAD
          git rm --cached . -r
      # Force push over cloned repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: init"
          push_options: --force
