name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run lint

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run:  npm run coverage
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          commit-message: "chore: updating coverage badges"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
